### ISSUE TITLE
Fallback methods for 2 permissions (Notifications not in v1)

### ISSUE THREAD

**Issue by aayu24** [solocoinapp/solocoin-android#51]
Location
Notifications
Storage

**Comment by prasadpilla** [comment]
Prasad PillaLast Saturday at 15:55
@nronas one thing to pick now is enabling notification_permission, location_permission storage on backend
nronasLast Saturday at 15:56
tell me more about it, i am intrigued :smile:
whats the business case for those fields?
Prasad PillaLast Saturday at 15:58
so we were thinking to persist the permissions on the backend, so that we have this info even if user uninstalls the app. but i just realised as we spoke. we do require those permissions to be given on re-install @apats24 ?
So it doesn't really make sense to store them on the backend
That info is limited to app-install instance and not central
nronasLast Saturday at 15:59
yeah i think you are right there, app-permissions should be per installation
Job done, fastest feature implementation i have ever done :smile:
0 code maximum success :smile:
